name: Merge upstream branches
on:
  schedule:
     # actually, ~5 minutes is the highest
     # effective frequency you will get
    - cron:  '0 8 * * *'
jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Merge upstream
        run: |
          git config --global user.name 'Teng-xu'
          git config --global user.email 'xuteng@amazon.com'

          git checkout master
          git pull --unshallow
          git remote add upstream https://github.com/tensorflow/tensorflow.git
          git fetch upstream
          git merge --no-edit upstream/master
          git push
