name: Merge upstream branch 2.4
on:
  schedule:
     # actually, ~5 minutes is the highest
     # effective frequency you will get
    - cron:  '0 8 * * *'
jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: r2.4
      - name: Merge upstream 2.4
        run: |
          git config --global user.name 'Teng-xu'
          git config --global user.email 'xuteng@amazon.com'
          git checkout r2.4
          git pull --unshallow
          git remote add upstream https://github.com/tensorflow/tensorflow.git
          git fetch upstream
          git merge --no-edit upstream/r2.4
          git push
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2
      - name: Run CodeBuild
        uses: aws-actions/aws-codebuild-run-build@v1.0.3
        with:
          project-name: Tensorflow-git-auto-sync-2-4

